### ISSUE TITLE
Hub Docker date problem on Raspberry pi 4

### ISSUE THREAD

**Issue by gallofeliz** [deftwork/samba#18]
Hi,

I use Raspberry pi 4 and my docker-compose was :
```
image: elswork/samba
```

Because of fail to login, I see the log (syslog) STATUS_INVALID_LOGON_HOURS. I entered `sudo docker-compose exec samba date` and seen `Mon Jun 15 16:41:36 CEST 2071`

The date is incorrect because we will not be in life in 2071 (planet destroyed).

I builded on my own (with alpine 3.12 because alpine is KO from 3.13 on raspberry) :
```
    build:
      context: https://github.com/deftwork/samba.git
      args:
        BASEIMAGE: alpine:3.12
```

And the date is correct and the login works.

FYI :)

Regards,
