### ISSUE TITLE
When using rootless Docker, the file owner is a non-existing user

### ISSUE THREAD

**Issue by weeix** [deftwork/samba#33]
Hi,

I'm using Docker [rootless mode][1] and running `elswork/samba` by using this `docker-compose.yml` file:

```
services:
  samba:
    container_name: samba
    image: elswork/samba
    env_file:
      - .env
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./backups:/share/backups
    command:
      - -u1000:1000:myuser:myuser:mypassword
      - -sBackups:/share/backups:rw:myuser
    restart: always
```

However, when I tried to create a file from Windows, this error message appears:

![image](https://user-images.githubusercontent.com/6592791/163025259-d5d3b7a5-7632-4a64-b5ad-fd36629e2012.png)

I had to run `chmod 777 backups` to be able to create files. When I inspect the created file, the user is `100999:100999`:

```
-rwxr--r-- 1 100999 100999    0 Apr 13 01:02 'New Text Document.txt'
```

Is this normal behavior, or is it due to the fact that I'm in rootless mode?

Thanks.

[1]: https://docs.docker.com/engine/security/rootless/
